name: release

on:
  pull_request:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: golang:alpine
    steps:
      - name: Install libpcap-dev
        run: sudo apk add libpcap-dev build-base
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Build gomap
        run: CGO_ENABLED=1 go build -ldflags "-s -w -linkmode external -extldflags='-static'" -o gomap .
